version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    container_name: demo-zookeeper
    networks:
      - local_default
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
    ports:
      - 2182:2182

  kafka:
    image: confluentinc/cp-kafka:5.5.1
    container_name: demo-kafka
    depends_on:
      - zookeeper
    networks:
      - local_default
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8084"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - 9093:9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  schemaregistry:
#    image: confluentinc/cp-schema-registry:5.5.1
#    container_name: demo-schemaregistry
#    depends_on:
#      - zookeeper
#    networks:
#      - local_default
#    environment:
#      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2182"
#      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
#      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8084"
#    ports:
#      - 8084:8084

  restproxy:
    image: confluentinc/cp-kafka-rest:5.5.1
    container_name: demo-restproxy
    depends_on:
      - kafka
    networks:
      - local_default
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2182"
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schemaregistry:8084"
      KAFKA_REST_HOST_NAME: restproxy
      KAFKA_REST_BOOTSTRAP_SERVERS: "kafka:9093"
    ports:
      - 8082:8082

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.12.0
    hostname: ksqldb-server
    container_name: demo-ksqldb-server
    depends_on:
      - kafka
      - restproxy
    ports:
      - "8089:8089"
    networks:
      - local_default
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8089
      KSQL_BOOTSTRAP_SERVERS: kafka:9093
      KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: 1
      KSQL_KSQL_SINK_REPLICAS: 1
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schemaregistry:8084"
      KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET: "earliest"
      KSQL_KSQL_EXTENSION_DIR: "/etc/ksqldb/ext/"

  ksqldb-cli:
    image: confluentinc/ksqldb-cli:0.12.0
    container_name: demo-ksqldb-cli
    depends_on:
      - kafka
      - ksqldb-server
    networks:
      - local_default
    entrypoint: /bin/sh
    tty: true

  kafka-statements-service:
    container_name: kafka-statements-service
    image: kafka-statements-service-app:latest
    depends_on:
      - zookeeper
      - kafka
      - ksqldb-cli
    ports:
      - "1025:1025"
      - "5005:5005"
    networks:
      - local_default
      - exchangerateservicemock_bridge
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xms256m -Xmx512m"
      SERVER_PORT: 1025
      ERROR_LEVEL_SPRING: "INFO"
      ERROR_LEVEL_APP: "INFO"
      LOG_PATH: "/opt/logs/"
      BOOTSTRAP_SERVERS_CONFIG: kafka:9093
      APPLICATION_ID_CONFIG: kafka-statements-service
      REPLICATION_FACTOR_CONFIG: 1
      STATE_DIR_CONFIG: /tmp/kafka-streams
      NUM_STANDBY_REPLICAS_CONFIG: 1
      EXCHANGE_RATE_SERVICE_URL: http://exchange-rate-service:8080
      JWT_SECRET_KEY: SECRET_KEY_ANIL
      JWT_VALIDITY_MILLIS: 60000

networks:
  local_default:
  exchangerateservicemock_bridge:
    external: true
